### ISSUE TITLE
[Bug Report] Debug error occasionally on reload

### ISSUE THREAD

**Issue by Erieeroot** [MotherGinger/RecklessAbandon#28] opened 2024-08-14 20:31 UTC
**Describe the bug**

NOTE:  I confirmed that debugging is off in the options, so not sure why it is even throwing this.

When reloading the game, this error will sometimes appear in bugsack.  I believe it happens as the reload starts, and not after because the sack is green once the reload completes, and it shows the bug from the last session.

Not a real issue by any means, but since it appeared I thought I should at least report it.  Let me know if you want me to change or test anything, more than happy to :) 

**To Reproduce**
Reload the game.  Sometimes it takes a reload or two

**Expected behavior**
No lua error?  :)

**Screenshots**

> 1x RecklessAbandon/Core/Core.lua:256: attempt to index field 'debugging' (a nil value)
[string "@RecklessAbandon/Core/Core.lua"]:256: in function `Debug'
[string "@RecklessAbandon/Core/Renderer.lua"]:316: in function `GenerateQuestTable'
[string "@RecklessAbandon/Core/Core.lua"]:645: in function <RecklessAbandon/Core/Core.lua:644>
[string "=[C]"]: ?

> Locals:
self = <table> {
 abandonTooltipFormat = "|cFFFFFAB8%s|r

|cFFFFF569%s|r
|cFFB5FFEB%s|r"
 mylevel = 70
 modules = <table> {
 }
 groupAbandonTooltipFormat = "|cFFFFFAB8%s|r

|cFFFFF569%s|r"
 screenwidth = 2530
 github = "https://github.com/MotherGinger/RecklessAbandon/issues"
 isRetail = true
 data = <table> {
 }
 isClassic = false
 db = <table> {
 }
 questGroupsByName = <table> {
 }
 Options = <table> {
 }
 isBC = false
 classIcons = <table> {
 }
 DF = <table> {
 }
 locale = "enUS"
 isCata = false
 mynameRealm = "Erieeroot - Stormrage"
 wowbuild = 56110
 myLocalizedFaction = "Alliance"
 myrace = "NightElf"
 title = "|cFF80528CReckless Abandon|r"
 screenheight = 1353
 logLevels = <table> {
 }
 myclass = "DRUID"
 initialized = true
 myguid = "Player-60-0F1F91B8"
 loadedtime = 36392.676000
 private = <table> {
 }
 global = <table> {
 }
 baseName = "RecklessAbandon"
 charSettings = <table> {
 }
 myname = "Erieeroot"
 author = "Frauke Betz"
 myLocalizedRace = "Night Elf"
 classColors = <table> {
 }
 wowpatch = "11.0.2"
 resolution = "2530x1353"
 myfaction = "Alliance"
 groupButtonPool = <table> {
 }
 name = "RecklessAbandon"
 myrealm = "Stormrage"
 defaultModuleLibraries = <table> {
 }
 isWrath = false
 privateVars = <table> {
 }
 questButtonPool = <table> {
 }
 version = "3.0.0-beta.1"
 Libs = <table> {
 }
 orderedModules = <table> {
 }
 defaultModuleState = true
 callbacks = <table> {
 }
 myLocalizedClass = "Druid"
 enabledState = true
 LibsMinor = <table> {
 }
 myClassID = 11
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'debugging' (a nil value)"
L = <table> {
 About = "About"
 Left Click: Abandon all quests = "Left Click: Abandon all quests"
 Enable |cff888888/reckless exclude <questID>|r = "Enable |cff888888/reckless exclude <questID>|r"
 Adjust the amount of messages you will receive from actions taken against your quest log. = "Adjust the amount of messages you will receive from actions taken against your quest log."
 Debug Settings = "Debug Settings"
 Quest Type = "Quest Type"
 Slash Commands = "Slash Commands"
 Enable |cff888888/reckless abandon <questID>|r = "Enable |cff888888/reckless abandon <questID>|r"
 Automatically abandon quests of the given type if they are included in group abandons. = "Automatically abandon quests of the given type if they are included in group abandons."
 Abandoning quests from the command line is currently |cFFFF6B6Bdisabled|r. You can enable it in the configuration settings |cff888888/reckless config|r = "Abandoning quests from the command line is currently |cFFFF6B6Bdisabled|r. You can enable it in the configuration settings |cff888888/reckless config|r"
 covenant callings = "covenant callings"
 %s is already excluded from group abandons! = "%s is already excluded from group abandons!"
 Configuration = "Configuration"
 Excluding quests from the command line is currently |cFFFF6B6Bdisabled|r. You can enable it in the configuration settings |cff888888/reckless config|r = "Excluding quests from the command line is currently |cFFFF6B6Bdisabled|r. You can enable it in the configuration settings |cff888888/reckless config|r"
 Campaign Quests = "Campaign Quests"
 Matches all red quests. = "Matches all red quests."
 Enable |cff888888/reckless list all|r = "Enable |cff888888/reckless list all|r"
 |cFFFF6B6BCaution: This can cause you to accidently toggle exclusion of a quest from group abandons when trying to track a quest in your quest log.|r = "|cFFFF6B6BCaution: This can cause you to accidently toggle exclusion of a quest from group abandons when trying to track a quest in your quest log.|r"
 Are you sure you want to abandon all quests in |cFFF2E699%s|r? = "Are you sure you want to abandon all quests in |cFFF2E699%s|r?"
 |cFFFF6B6BCaution: This can cause you to accidently abandon all quests in a zone when trying to expand a zone header in your quest log.|r = "|cFFFF6B6BCaution: This can cause you to accidently abandon all quests in a zone when trying to expand a zone header in your `

**Additional context**

**Comment by MotherGinger** [comment] 2024-08-21 22:12
Thank you for the report! I will look into this tonight and will keep you posted

**Comment by MotherGinger** [comment] 2024-08-21 22:26
I have implemented a fix in v3.0.0-beta.2 since it looks like you are running v3.0.0-beta.1 :)

Please let me know if you see this issue again

**Comment by MotherGinger** [comment] 2024-08-24 22:04
In was able to actually reproduce this (a race condition) and have a true fix for beta.3 that I will be making available soon

**Comment by Erieeroot** [comment] 2024-08-25 00:27
Sorry I missed your original reply...busy with work and then early access :)

Sounds good :D

**Comment by MotherGinger** [comment] 2024-08-31 23:12
@Erieeroot Please check out https://github.com/MotherGinger/RecklessAbandon/releases/tag/v3.0.0-beta.3

I will close this issue for now, feel free to reopen it if you encounter this issue still

**Closed by MotherGinger** 2024-08-31 23:12 UTC
Labels: type: bug, priority: medium, status: completed
